name: gladiators
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit: ^3.0.0
  ecdsa: ^0.0.4
  elliptic: ^0.3.8
  hex: ^0.2.0
  tuple: ^2.0.0

dev_dependencies:
  test: ^1.16.5
  conduit_test: ^3.0.0
